# Generate catalog.md with one subheading and @example block per category (keeps doc in sync as catalog grows).
# Requires PowerSystemCaseBuilder to be loaded (e.g. from docs/make.jl).

function generate_catalog_md()
    catalog = PowerSystemCaseBuilder.SystemCatalog()
    categories = PowerSystemCaseBuilder.list_categories(catalog)
    lines = ["<!-- Generated by docs/make.jl from the system catalog. Do not edit by hand. -->", "", "# Full Catalog of `System`s", ""]
    # First block: setup shared session
    push!(lines, "```@setup cat")
    push!(lines, "using PowerSystemCaseBuilder")
    push!(lines, "catalog = SystemCatalog()")
    push!(lines, "```")
    push!(lines, "")
    for cat in categories
        name = string(nameof(cat))
        push!(lines, "[`$(name)`](@ref)")
        push!(lines, "")
        push!(lines, "```@example cat")
        push!(lines, "show_systems(catalog, $(name)) #hide")
        push!(lines, "```")
        push!(lines, "")
    end
    return join(lines, "\n")
end
